# Generated by Django 5.1.1 on 2026-04-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_yamdbuser_confirmation_code_alter_yamdbuser_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yamdbuser',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
