# Generated by Django 5.1.1 on 2026-04-09 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_pendinguser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PendingUser',
        ),
    ]
