# Generated by Django 6.0.4 on 2026-04-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_delete_pendinguser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yamdbuser',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Биография пользователя'),
        ),
        migrations.AlterField(
            model_name='yamdbuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='yamdbuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Фамилия'),
        ),
    ]
