# Generated by Django 6.0.4 on 2026-04-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_yamdbuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yamdbuser',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
