# Generated by Django 6.0.4 on 2026-04-14 07:22

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_yamdbuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yamdbuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[users.models.valid_username], verbose_name='Имя пользователя'),
        ),
    ]
